Asking for better config template
ishefi/semantle-he pull request #41
Opened 2022-04-30 12:59 UTC by shushui

Out of trying out the app, I am guessing the format of the configuration.
(I am new to Python, so maybe I also miss some common-python-knowledge I don't know of)

2022-04-30 14:15 UTC, ishefi requested changes

2022-04-30 14:15 UTC, ishefi commented on semantle.cfg.format
> +redis="42"
should be a redis url string 
```
redis = 'redis://USERNAME:PASSWORD@HOST:PORT/'
```

2022-04-30 14:15 UTC, ishefi commented on semantle.cfg.format
> +quotes="dd"
```python
quotes: [Tuple[str,str,str,str]] = [
(
    QOUTE,
    QOUTEE,
    SOURCE,
    URL
)
```

2022-04-30 14:15 UTC, ishefi commented on semantle.cfg.format
> +easter_eggs= "42"
```python
easter_eggs: Dict[str,str] = {EASTER: EGG}
```

2022-04-30 14:26 UTC, ishefi commented on README.md
> +Configurations should be set in a `semantle.cfg` file, following the example `semantle.cfg.format`.
it's actually _can_ and not _should_, as you can pass the entire configuration through env var `HS_CONFIG`

2022-11-27 07:29 UTC, Iddoyadlin commented
there is now a better template (see config.format.yaml)

2022-11-27 07:29 UTC, closed without merging